# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    name: Checks
    steps:
    - uses: actions/checkout@v4
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run mypy
      run: |
        pip install --upgrade pip
        python -m pip install -e ".[dev]"
        mypy --strict sparta
      continue-on-error: true
    - name: Run flake8
      run: |
        pip install --upgrade pip
        python -m pip install -e ".[dev]"
        flake8 .
      continue-on-error: true
    - name: Run docstring coverage
      run: |
        pip install --upgrade pip
        python -m pip install -e ".[dev]"
        docstr-coverage sparta --skip-init --skip-file-doc --skip-private --verbose=3 --fail-under=100
